#-------------------------------------------
# This script aims to build an LPA model
#
# NOTE: This script requires setup.R to
# have been run first
#-------------------------------------------

#-------------------------------------------
# Author: Trent Henderson, 11 September 2020
#-------------------------------------------

#------------------------- MODEL SPECIFICATION ---------------------

m1 <- d2[1:nrow(d2), ] %>%
  select(detachment, relaxation, mastery, control) %>%
  single_imputation() %>%
  estimate_profiles(1:6,
                    variances = c("equal", "varying"),
                    covariances = c("zero", "varying"))

#------------------------- OUTPUTS ---------------------------------

#-----------------
# FIT INDICES
#-----------------

m1 %>%
  compare_solutions(statistics = c("AIC", "BIC", "AWE", "CLC", "KIC"))

#-----------------
# DEFAULT LPA PLOT
#-----------------

# Plot LPA

m1 %>%
  plot_profiles()

#-----------------
# FIT STATISTICS
#-----------------

# Get fit statistics

get_fit(m1)

#-----------------
# COLLECT OUTPUTS
#-----------------

# Get outputs in a dataframe

lpa_outputs <- get_data(m1)

# Filter to just Model 1/Classes 4 as this model had the best BIC value

lpa_outputs_filt <- lpa_outputs %>%
  filter(model_number == "1" & classes_number == 4)

# Join back in to main dataset

d3 <- d2 %>%
  inner_join(lpa_outputs_filt, by = c("detachment" = "detachment", "relaxation" = "relaxation",
                                      "mastery" = "mastery", "control" = "control")) %>%
  filter(Probability > 0.8) %>%
  mutate(Class = as.factor(Class)) %>%
  mutate(gender = as.factor(gender))

#------------------------
# ANALYSIS OF CLASSES
#------------------------

class_desc <- d3 %>%
  dplyr::select(c(detachment, relaxation, mastery, control, Class)) %>%
  gather(key = metric, value = value, 1:4) %>%
  mutate(metric = str_to_title(metric))

p <- class_desc %>%
  ggplot(aes(x = value)) +
  geom_density(aes(fill = Class), colour = "#05445E", alpha = 0.5) +
  labs(title = "Distribution of recovery experiences by recovery profile",
       subtitle = "Recovery profiles were generated by LPA",
       x = "Value",
       y = "Density",
       fill = "Recovery Profile") +
  scale_fill_manual(values = c("#FEB06A", "#189AB4", "#75E6DA", "#FD62AD")) +
  theme_bw() +
  theme(legend.position = "bottom",
        panel.grid.minor = element_blank()) +
  facet_wrap(~metric)
print(p)

# Export graph

CairoPNG("output/profile-density.png", 800, 600)
print(p)
dev.off()
